### ISSUE TITLE
New Luna Studio testing

### ISSUE THREAD

**Issue by kustosz** [luna/luna-core#113]
Includes tracking of:
– Core problems (wrong typechecks / interpretation results etc.)
– State mismatches between backend and GUI (things like BreadcrumbDoesNotExist etc.)
– Double representation bugs – mismatched states between graphs and text rep

**Comment by sylwiabr** [comment]
Issue moved to [luna/internal #51](https://github.com/luna/internal/issues/51) via [**ZenHub**](https://www.zenhub.com/)
